"""Backend tests for the paginated /v2 file listing.

See spec: spec dated 2026-05-29 (pagination-v2 design).
"""

from another_s3_manager.s3_client import (
    list_objects_client_load_for_role,
    list_objects_paginated_for_role,
)


def _seed(moto_s3, bucket: str, *, files: list[str], directories: list[str]) -> None:
    """Pre-populate a bucket with empty-body files plus empty directory markers.

    Directory markers use a key that ends with `/` and zero body. This is the
    canonical S3 directory-marker shape — `list_objects_paginated_for_role`
    explicitly skips it (matches the existing `list_objects_for_role` filter),
    so sub-path tests (path="dir1") never see a stray `.keep` leak through.
    """
    moto_s3.create_bucket(Bucket=bucket)
    for f in files:
        moto_s3.put_object(Bucket=bucket, Key=f, Body=b"")
    for d in directories:
        moto_s3.put_object(Bucket=bucket, Key=f"{d}/", Body=b"")


def test_paginated_first_page_returns_directories_and_first_files(moto_s3):
    """First call (no continuation_token) returns CommonPrefixes as
    `directories` plus the first `max_keys` files."""
    _seed(
        moto_s3,
        "paginated-alpha",
        files=["a.txt", "b.txt", "c.txt", "d.txt", "e.txt"],
        directories=["dir1", "dir2"],
    )

    result = list_objects_paginated_for_role(
        role=None,
        bucket="paginated-alpha",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_keys=2,
    )

    # CommonPrefixes from this bucket should land in `directories`, both of them.
    dir_names = [d["name"] for d in result["directories"]]
    assert dir_names == ["dir1", "dir2"]
    assert all(d["is_directory"] is True for d in result["directories"])

    # max_keys=2 means at most 2 file entries on this page.
    assert len(result["files"]) == 2
    assert result["files"][0]["name"] == "a.txt"
    assert result["files"][1]["name"] == "b.txt"
    assert all(f["is_directory"] is False for f in result["files"])

    # IsTruncated → next_token + has_more=True.
    assert result["has_more"] is True
    assert result["next_token"] is not None
    assert isinstance(result["next_token"], str) and len(result["next_token"]) > 0


def test_paginated_continuation_excludes_directories(moto_s3):
    """The second page (continuation_token is set) returns directories=[]."""
    _seed(
        moto_s3,
        "paginated-beta",
        files=["a.txt", "b.txt", "c.txt", "d.txt", "e.txt"],
        directories=["dir1", "dir2"],
    )

    page1 = list_objects_paginated_for_role(
        role=None,
        bucket="paginated-beta",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_keys=2,
    )
    assert page1["has_more"] is True

    page2 = list_objects_paginated_for_role(
        role=None,
        bucket="paginated-beta",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_keys=2,
        continuation_token=page1["next_token"],
    )
    assert page2["directories"] == []
    file_names = [f["name"] for f in page2["files"]]
    assert file_names == ["c.txt", "d.txt"]
    assert page2["has_more"] is True


def test_paginated_last_page_clears_token(moto_s3):
    """The final page returns next_token=None and has_more=False."""
    _seed(
        moto_s3,
        "paginated-gamma",
        files=["a.txt", "b.txt", "c.txt"],
        directories=[],
    )

    page1 = list_objects_paginated_for_role(
        role=None,
        bucket="paginated-gamma",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_keys=2,
    )
    page2 = list_objects_paginated_for_role(
        role=None,
        bucket="paginated-gamma",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_keys=2,
        continuation_token=page1["next_token"],
    )
    # Last page returns one file (c.txt). last_modified is generated by moto;
    # we assert the rest of the entry shape and equality on name/size only.
    assert len(page2["files"]) == 1
    assert page2["files"][0]["name"] == "c.txt"
    assert page2["files"][0]["is_directory"] is False
    assert page2["files"][0]["size"] == 0
    assert page2["next_token"] is None
    assert page2["has_more"] is False


def test_paginated_files_sorted_case_insensitive(moto_s3):
    """Files within a page are sorted case-insensitive by name."""
    _seed(
        moto_s3,
        "paginated-sort",
        files=["Beta.txt", "alpha.txt", "Charlie.txt"],
        directories=[],
    )

    result = list_objects_paginated_for_role(
        role=None,
        bucket="paginated-sort",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_keys=10,
    )
    names = [f["name"] for f in result["files"]]
    assert names == ["alpha.txt", "Beta.txt", "Charlie.txt"]


def test_route_legacy_mode_unchanged(app_client, moto_s3):
    """Without max_keys the route returns the legacy envelope."""
    from tests.test_main import login

    _, headers = login(app_client)
    _seed(moto_s3, "legacy-bucket", files=["a.txt", "b.txt"], directories=[])

    response = app_client.get(
        "/api/buckets/legacy-bucket/files",
        headers=headers,
    )
    assert response.status_code == 200
    body = response.json()
    # Legacy shape: {files, path, total_count}; no directories/next_token/has_more keys.
    assert "directories" not in body
    assert "next_token" not in body
    assert "has_more" not in body
    assert body["path"] == ""
    assert body["total_count"] == 2
    assert {f["name"] for f in body["files"]} == {"a.txt", "b.txt"}


def test_route_paginated_mode_returns_new_envelope(app_client, moto_s3):
    """With max_keys the route returns {directories, files, next_token, has_more}."""
    from tests.test_main import login

    _, headers = login(app_client)
    _seed(
        moto_s3,
        "paginated-route",
        files=["a.txt", "b.txt", "c.txt"],
        directories=["dir1"],
    )

    response = app_client.get(
        "/api/buckets/paginated-route/files?max_keys=2",
        headers=headers,
    )
    assert response.status_code == 200
    body = response.json()
    assert {d["name"] for d in body["directories"]} == {"dir1"}
    assert len(body["files"]) == 2
    assert body["has_more"] is True
    assert body["next_token"] is not None


def test_route_max_keys_out_of_range_rejected(app_client, moto_s3):
    """max_keys=5000 → 422 (FastAPI Query le=1000 validation)."""
    from tests.test_main import login

    _, headers = login(app_client)
    moto_s3.create_bucket(Bucket="rejected")

    response = app_client.get(
        "/api/buckets/rejected/files?max_keys=5000",
        headers=headers,
    )
    assert response.status_code == 422  # FastAPI validation error code


def test_route_continuation_without_max_keys_rejected(app_client, moto_s3):
    """continuation_token without max_keys → 400 with explanatory message."""
    from tests.test_main import login

    _, headers = login(app_client)
    moto_s3.create_bucket(Bucket="orphan-token")

    response = app_client.get(
        "/api/buckets/orphan-token/files?continuation_token=abc",
        headers=headers,
    )
    assert response.status_code == 400
    assert "max_keys" in response.json()["detail"]


def test_client_load_returns_all_when_under_limit(moto_s3):
    """When the folder fits under the limit, truncated=False and all files return."""
    _seed(
        moto_s3,
        "client-small",
        files=[f"f{i:03d}.txt" for i in range(5)],
        directories=["dir1"],
    )

    result = list_objects_client_load_for_role(
        role=None,
        bucket="client-small",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_client_load=10,
    )

    assert result["truncated"] is False
    assert result["next_token"] is None
    assert [d["name"] for d in result["directories"]] == ["dir1"]
    assert len(result["files"]) == 5


def test_client_load_truncates_at_limit(moto_s3):
    """When the folder exceeds the limit, exactly limit files return + truncated=True."""
    _seed(
        moto_s3,
        "client-big",
        files=[f"f{i:04d}.txt" for i in range(12)],
        directories=[],
    )

    result = list_objects_client_load_for_role(
        role=None,
        bucket="client-big",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_client_load=5,
    )

    assert result["truncated"] is True
    assert result["next_token"] is not None
    assert len(result["files"]) == 5
    assert [f["name"] for f in result["files"]] == [f"f{i:04d}.txt" for i in range(5)]


def test_client_load_continuation_appends_next_chunk(moto_s3):
    """Passing next_token resumes and returns the following chunk."""
    _seed(
        moto_s3,
        "client-cont",
        files=[f"f{i:04d}.txt" for i in range(12)],
        directories=[],
    )

    page1 = list_objects_client_load_for_role(
        role=None,
        bucket="client-cont",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_client_load=5,
    )
    page2 = list_objects_client_load_for_role(
        role=None,
        bucket="client-cont",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_client_load=5,
        continuation_token=page1["next_token"],
    )

    assert page2["directories"] == []
    names = [f["name"] for f in page2["files"]]
    assert names == [f"f{i:04d}.txt" for i in range(5, 10)]
    assert page2["truncated"] is True
    assert page2["next_token"] is not None


def test_client_load_folder_heavy_is_bounded_and_terminates(moto_s3):
    """A level with many sub-folders and NO files returns a bounded chunk.

    Regression: previously the file loop counted only files toward
    max_client_load, so a folder dominated by sub-folders (real case: 600k
    sub-folders, zero files) paginated the entire keyspace hunting for files
    that don't exist, hanging the request. Directories now count toward the
    budget, so the chunk is bounded and the file loop never runs.
    """
    _seed(
        moto_s3,
        "folder-heavy",
        files=[],
        directories=[f"d{i:04d}" for i in range(400)],
    )

    result = list_objects_client_load_for_role(
        role=None,
        bucket="folder-heavy",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_client_load=300,
    )

    # Folders count toward the budget: capped at exactly max_client_load.
    assert len(result["directories"]) == 300
    assert [d["name"] for d in result["directories"]] == [f"d{i:04d}" for i in range(300)]
    assert result["files"] == []
    # More sub-folders exist beyond this chunk → truncated indicator.
    assert result["truncated"] is True


def test_client_load_folder_heavy_makes_few_s3_calls(monkeypatch):
    """Regression guard: a sub-folder-dominated level must not fan out into many
    ListObjectsV2 calls. A fake, inexhaustible folder keyspace (every page is
    CommonPrefixes, IsTruncated forever) would loop endlessly under the old
    code; the fake raises past a small call budget so a regression fails loudly
    instead of hanging the suite.
    """
    from another_s3_manager import s3_client

    calls = {"n": 0}

    class FakeS3:
        def list_objects_v2(self, **kwargs):
            calls["n"] += 1
            if calls["n"] > 5:
                raise RuntimeError(f"grind detected: {calls['n']} ListObjectsV2 calls")
            max_keys = kwargs.get("MaxKeys", 1000)
            prefixes = [{"Prefix": f"d{i:06d}/"} for i in range(min(max_keys, 1000))]
            return {
                "CommonPrefixes": prefixes,
                "Contents": [],
                "IsTruncated": True,
                "NextContinuationToken": "tok",
            }

    monkeypatch.setattr(s3_client, "get_s3_client", lambda role_name=None: FakeS3())

    result = s3_client.list_objects_client_load_for_role(
        role=None,
        bucket="whatever",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_client_load=300,
    )

    # Only the directory-discovery call runs; the file loop is skipped because
    # sub-folders already filled the budget.
    assert calls["n"] == 1
    assert len(result["directories"]) == 300
    assert result["files"] == []
    assert result["truncated"] is True


def test_config_has_max_client_load_default(monkeypatch, tmp_path):
    """A fresh config exposes max_client_load defaulting to 10000."""
    import importlib

    import another_s3_manager.config as config_module

    cfg_path = tmp_path / "config.json"
    monkeypatch.setenv("S3_FILE_MANAGER_CONFIG", str(cfg_path))
    importlib.reload(config_module)
    config_module._config_cache = {}
    config_module._config_mtime = 0

    config = config_module._get_default_config()
    assert config["max_client_load"] == 10000


def test_route_client_load_mode_under_limit(app_client, moto_s3):
    """client_load=1 with small folder → {directories, files, truncated:false}."""
    from tests.test_main import login

    _, headers = login(app_client)
    _seed(moto_s3, "cl-small", files=["a.txt", "b.txt"], directories=["d1"])

    response = app_client.get(
        "/api/buckets/cl-small/files?client_load=1",
        headers=headers,
    )
    assert response.status_code == 200
    body = response.json()
    assert {d["name"] for d in body["directories"]} == {"d1"}
    assert {f["name"] for f in body["files"]} == {"a.txt", "b.txt"}
    assert body["truncated"] is False
    assert body["next_token"] is None


def test_route_client_load_mode_truncates(app_client, moto_s3):
    """client_load with max_keys below folder size → truncated:true."""
    from tests.test_main import login

    _, headers = login(app_client)
    _seed(moto_s3, "cl-big", files=[f"f{i:03d}.txt" for i in range(8)], directories=[])

    response = app_client.get(
        "/api/buckets/cl-big/files?client_load=1&max_keys=3",
        headers=headers,
    )
    assert response.status_code == 200
    body = response.json()
    assert len(body["files"]) == 3
    assert body["truncated"] is True
    assert body["next_token"] is not None


def test_route_config_exposes_max_client_load(app_client, moto_s3):
    """/api/config includes max_client_load."""
    from tests.test_main import login

    _, headers = login(app_client)
    response = app_client.get("/api/config", headers=headers)
    assert response.status_code == 200
    assert response.json()["max_client_load"] == 10000


def test_update_config_preserves_max_client_load_when_omitted(app_client, moto_s3):
    """POST /api/config without max_client_load keeps the saved value.

    Every other config field has a preserve-on-omit block in update_config;
    max_client_load must too, else an API client (curl / MCP / an older frontend)
    that saves config without the field silently resets the admin-configured
    value back to the 10000 default.
    """
    from tests.test_main import login

    _, headers = login(app_client)
    # Save a non-default value.
    r1 = app_client.post(
        "/api/config",
        json={"roles": [], "max_client_load": 500},
        headers=headers,
    )
    assert r1.status_code == 200, r1.json()
    # Save again WITHOUT max_client_load — it must be preserved, not reset.
    r2 = app_client.post(
        "/api/config",
        json={"roles": []},
        headers=headers,
    )
    assert r2.status_code == 200, r2.json()
    resp = app_client.get("/api/config", headers=headers)
    assert resp.json()["max_client_load"] == 500
