"""Backend tests for the paginated /v2 file listing.

See spec: spec dated 2026-05-29 (pagination-v2 design).
"""

from another_s3_manager.s3_client import list_objects_paginated_for_role


def _seed(moto_s3, bucket: str, *, files: list[str], directories: list[str]) -> None:
    """Pre-populate a bucket with empty-body files plus empty directory markers.

    Directory markers use a key that ends with `/` and zero body. This is the
    canonical S3 directory-marker shape — `list_objects_paginated_for_role`
    explicitly skips it (matches the existing `list_objects_for_role` filter),
    so sub-path tests (path="dir1") never see a stray `.keep` leak through.
    """
    moto_s3.create_bucket(Bucket=bucket)
    for f in files:
        moto_s3.put_object(Bucket=bucket, Key=f, Body=b"")
    for d in directories:
        moto_s3.put_object(Bucket=bucket, Key=f"{d}/", Body=b"")


def test_paginated_first_page_returns_directories_and_first_files(moto_s3):
    """First call (no continuation_token) returns CommonPrefixes as
    `directories` plus the first `max_keys` files."""
    _seed(
        moto_s3,
        "paginated-alpha",
        files=["a.txt", "b.txt", "c.txt", "d.txt", "e.txt"],
        directories=["dir1", "dir2"],
    )

    result = list_objects_paginated_for_role(
        role=None,
        bucket="paginated-alpha",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_keys=2,
    )

    # CommonPrefixes from this bucket should land in `directories`, both of them.
    dir_names = [d["name"] for d in result["directories"]]
    assert dir_names == ["dir1", "dir2"]
    assert all(d["is_directory"] is True for d in result["directories"])

    # max_keys=2 means at most 2 file entries on this page.
    assert len(result["files"]) == 2
    assert result["files"][0]["name"] == "a.txt"
    assert result["files"][1]["name"] == "b.txt"
    assert all(f["is_directory"] is False for f in result["files"])

    # IsTruncated → next_token + has_more=True.
    assert result["has_more"] is True
    assert result["next_token"] is not None
    assert isinstance(result["next_token"], str) and len(result["next_token"]) > 0


def test_paginated_continuation_excludes_directories(moto_s3):
    """The second page (continuation_token is set) returns directories=[]."""
    _seed(
        moto_s3,
        "paginated-beta",
        files=["a.txt", "b.txt", "c.txt", "d.txt", "e.txt"],
        directories=["dir1", "dir2"],
    )

    page1 = list_objects_paginated_for_role(
        role=None,
        bucket="paginated-beta",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_keys=2,
    )
    assert page1["has_more"] is True

    page2 = list_objects_paginated_for_role(
        role=None,
        bucket="paginated-beta",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_keys=2,
        continuation_token=page1["next_token"],
    )
    assert page2["directories"] == []
    file_names = [f["name"] for f in page2["files"]]
    assert file_names == ["c.txt", "d.txt"]
    assert page2["has_more"] is True


def test_paginated_last_page_clears_token(moto_s3):
    """The final page returns next_token=None and has_more=False."""
    _seed(
        moto_s3,
        "paginated-gamma",
        files=["a.txt", "b.txt", "c.txt"],
        directories=[],
    )

    page1 = list_objects_paginated_for_role(
        role=None,
        bucket="paginated-gamma",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_keys=2,
    )
    page2 = list_objects_paginated_for_role(
        role=None,
        bucket="paginated-gamma",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_keys=2,
        continuation_token=page1["next_token"],
    )
    # Last page returns one file (c.txt). last_modified is generated by moto;
    # we assert the rest of the entry shape and equality on name/size only.
    assert len(page2["files"]) == 1
    assert page2["files"][0]["name"] == "c.txt"
    assert page2["files"][0]["is_directory"] is False
    assert page2["files"][0]["size"] == 0
    assert page2["next_token"] is None
    assert page2["has_more"] is False


def test_paginated_files_sorted_case_insensitive(moto_s3):
    """Files within a page are sorted case-insensitive by name."""
    _seed(
        moto_s3,
        "paginated-sort",
        files=["Beta.txt", "alpha.txt", "Charlie.txt"],
        directories=[],
    )

    result = list_objects_paginated_for_role(
        role=None,
        bucket="paginated-sort",
        path="",
        user_dict={"username": "admin", "is_admin": True, "allowed_roles": []},
        max_keys=10,
    )
    names = [f["name"] for f in result["files"]]
    assert names == ["alpha.txt", "Beta.txt", "Charlie.txt"]


def test_route_legacy_mode_unchanged(app_client, moto_s3):
    """Without max_keys the route returns the legacy envelope."""
    from tests.test_main import login

    _, headers = login(app_client)
    _seed(moto_s3, "legacy-bucket", files=["a.txt", "b.txt"], directories=[])

    response = app_client.get(
        "/api/buckets/legacy-bucket/files",
        headers=headers,
    )
    assert response.status_code == 200
    body = response.json()
    # Legacy shape: {files, path, total_count}; no directories/next_token/has_more keys.
    assert "directories" not in body
    assert "next_token" not in body
    assert "has_more" not in body
    assert body["path"] == ""
    assert body["total_count"] == 2
    assert {f["name"] for f in body["files"]} == {"a.txt", "b.txt"}


def test_route_paginated_mode_returns_new_envelope(app_client, moto_s3):
    """With max_keys the route returns {directories, files, next_token, has_more}."""
    from tests.test_main import login

    _, headers = login(app_client)
    _seed(
        moto_s3,
        "paginated-route",
        files=["a.txt", "b.txt", "c.txt"],
        directories=["dir1"],
    )

    response = app_client.get(
        "/api/buckets/paginated-route/files?max_keys=2",
        headers=headers,
    )
    assert response.status_code == 200
    body = response.json()
    assert {d["name"] for d in body["directories"]} == {"dir1"}
    assert len(body["files"]) == 2
    assert body["has_more"] is True
    assert body["next_token"] is not None


def test_route_max_keys_out_of_range_rejected(app_client, moto_s3):
    """max_keys=5000 → 422 (FastAPI Query le=1000 validation)."""
    from tests.test_main import login

    _, headers = login(app_client)
    moto_s3.create_bucket(Bucket="rejected")

    response = app_client.get(
        "/api/buckets/rejected/files?max_keys=5000",
        headers=headers,
    )
    assert response.status_code == 422  # FastAPI validation error code


def test_route_continuation_without_max_keys_rejected(app_client, moto_s3):
    """continuation_token without max_keys → 400 with explanatory message."""
    from tests.test_main import login

    _, headers = login(app_client)
    moto_s3.create_bucket(Bucket="orphan-token")

    response = app_client.get(
        "/api/buckets/orphan-token/files?continuation_token=abc",
        headers=headers,
    )
    assert response.status_code == 400
    assert "max_keys" in response.json()["detail"]
