"""drop tour_seen_v1

Revision ID: 6e601cabdb60
Revises: fbed2efcaa7a
Create Date: 2026-05-07 21:52:25.958319

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e601cabdb60"
down_revision: Union[str, Sequence[str], None] = "fbed2efcaa7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("tour_seen_v1")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tour_seen_v1", sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))

    # ### end Alembic commands ###
