"""add tour_seen_v1 to users

Revision ID: 7d34318962ca
Revises: 48449103e33c
Create Date: 2026-05-01 13:30:56.509954

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d34318962ca"
down_revision: Union[str, Sequence[str], None] = "48449103e33c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tour_seen_v1", sa.Boolean(), server_default="0", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("tour_seen_v1")

    # ### end Alembic commands ###
